# Generated by Django 2.1.3 on 2018-12-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucketlist',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
