# Generated by Django 2.1.3 on 2018-12-19 09:50

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bucketlist_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketlist',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[api.models.validate_cost]),
        ),
    ]
